title = "Gitleaks Full Scan"
description = "Scan all files for anything that looks like secrets"

[[rules]]
description = "Catch everything for testing"
regex = '.*'       # matches any content
tags = ["test"]
